 			<footer>
	        	<!-- le footer qui contients mentions legals ,liens partenairs etc -->
	        	<h3>©Gerwin Software - Tous droits réservés.</h3>
	        	<section>
	        		<ul>
		        		<li><a href="#" title="Faq">FAQ</a></li>
		        		<li><a href="#" title="Mentions legales">Mentions Legales</a></li>
		        		<li><a href="#" title="Gerwin recrute">GERWIN RECRUTE !</a></li>
		        	</ul>
		        	<ul>
		        		<li><a href="#" title="Faq">FAQ</a></li>
		        		<li><a href="#" title="Mentions legales">Mentions Legales</a></li>
		        		<li><a href="#" title="Gerwin recrute">GERWIN RECRUTE !</a></li>
		        	</ul>
		        	<ul>
		        		<li><a href="https://www.facebook.com" title="www.facebook.com"><img id="logo1" src="img\Flogo2.png" alt="logo facebook" /></a></li>
		        		<li><a href="https://twitter.com/login?lang=fr" title="www.twitter.com"><img id="logo2" src="img\Tlogo2.png" alt="logo twitter" /></a></li>
		        		<li><a href="https://www.pinterest.fr/" title="www.pinterest.com"><img id="logo3" src="img\Plogo2.png" alt="logo pinterest" /></a></li>
		        		<li><a href="https://www.instagram.com/?hl=fr" title="www.instagram.com"><img id="logo4" src="img\Ilogo2.png" alt="logo instagram" /></a></li>
	        		</ul>
	        	</section>

	        </footer>
  		</div>
  		
  		<?php if ($reference == 'games') { ?>
  			<script src= "script.js"> </script>
  		<?php } ?>
		<!-- <script src= "script.js"> </script> -->
	</body>
	
</HTML>