			<main>
				<!-- le main est un conteneur avec un border jusqu'au footer -->
	            <div id="bloc1">
	            	<!-- gros rectangle de gauche disposition titre/bloctext verticals,puis image/text en flex deux fois  avec un border right -->
	            	<h1><strong>Quiz Panic</strong></h1>
					<section>
	            		<img id="qp0" src="img\QP0.png" alt="Images demo Quiz Panic" />
	            		<p>3 modes de jeu
	            			</br></br>-> Mode Panic : de 4 à 6 joueurs s’affrontent sur des quizz de 5 questions ! Les meilleurs se qualifient pour le mode Chaos !
	            			</br></br>-> Mode Chaos : 20 joueurs, 10 questions, des éliminations, des questions spéciales … de la pure folie !
	            			</br></br>-> Mode Amis : affronte de 1 à 10 amis en Live !</p>
	            	</section>
	            	<section>
						<p>Quiz Panic est un jeu de quiz de culture générale réunissant de 2 à 20 adversaires qui s’affrontent en live. Votre mission principale est de faire évoluer votre quizzy, un petit personnage adorable qui sera votre digne représentant dans le jeu. En effet, celui-ci devra arpenter les 100 cases d’une carte de progression, qui correspondent chacune à une mission à réaliser dans le quiz. Toutes les dix missions réussies, votre quizzy évoluera et changera ainsi d’apparence.Les Quizzies sont un peu limités, avec leur mémoire de poisson rouge et leur demi-neurone. C'est donc à toi de les aider à devenir des champions du quizz de culture générale !</p>
						<img id="qp1" src="img\QP.png" title="Quiz Panic" alt="Image Quiz Panic" />					
	            	</section>
	            	<section>
	            		<img class="qp2" src="img\apstore.png" title="Quiz Panic" alt="Image Quiz Panic" />
	            		<p>QUIZ PANIC DISPONIBLE SUR IOS
Après un carton monumental sur Android (jeu de quiz le mieux noté du store avec 4.6/5), Quiz Panic vient secouer l'Appstore !!!</p>
	            	</section>
	            	<section>
	            		<img class="qp2" src="img\plstore.png" title="Quiz Panic" alt="Image Quiz Panic" />
	            		<p>QUIZ PANIC EST AUSSI DISPONIBLE SUR le Playstore</p>
	            	</section>
	            </div>
	        </main>