			<main>
				<!-- le main est un conteneur avec un border jusqu'au footer -->
	            <div id="bloc1gauche">
	            	<!-- gros rectangle de gauche disposition titre/bloctext verticals,puis image/text en flex deux fois  avec un border right -->
	            	<h1>Gerwin</h1>
	            	<p>Gerwin Software est un éditeur de jeux qui a le Web comme terrain de jeu, le fun comme credo, et le respect de sa communauté comme règle.
Connus pour nos jeux de connaissances qui ont révolutionné le Quiz en ligne, nous travaillons sans relâche à imaginer les jeux qui vous distrairont demain, en tirant le meilleur des dernières technologies Web et Mobiles.
Indépendants, autonomes et passionnés, nous maîtrisons la chaîne compète de la création des jeux depuis les concepts initiaux jusqu'à l’exploitation du jeu final sur le réseau.
Et, oui, nos bureaux sont à Aix en Provence !</p>
					<section>
	            		<img id="qp0" src="img\QP0.png" alt="Images demo Quiz Panic" />
	            		<p><strong>3 modes de jeu</strong>
	            			</br></br>-> Mode Panic : de 4 à 6 joueurs s’affrontent sur des quizz de 5 questions ! Les meilleurs se qualifient pour le mode Chaos !
	            			</br></br>-> Mode Chaos : 20 joueurs, 10 questions, des éliminations, des questions spéciales … de la pure folie !
	            			</br></br>-> Mode Amis : affronte de 1 à 10 amis en Live !</p>
	            	</section>
	            	<section>
	            		<img id="qp1" src="img\QP.png" title="Quiz Panic" alt="Image Quiz Panic" />
	            		<p>QUIZ PANIC DISPONIBLE SUR IOS
Après un carton monumental sur Android (jeu de quiz le mieux noté du store avec 4.6/5), Quiz Panic vient secouer l'Appstore !!!</p>
	            	</section>
	            	<section>
	            		<img id="qp2" src="img\QP.png" title="Quiz Panic" alt="Image Quiz Panic" />
	            		<p>QUIZ PANIC EST AUSSI DISPONIBLE SUR le Playstore</p>
	            	</section>
	            </div>

	            <div id="bloc2droite">
	            	<!-- petit carré en haut à droite disposition titre/image/bloctext verticals -->
	            	<h2>News</h2>
	            	<section>	            		
	            		<img id="qrevent" src="img\QR.png" title="Quiz Rush evenement" alt="Image Quiz Rush avec banière evenement de culture generale" />
	            		<p>Quiz Rush est la première course de culture générale Live et multijoueurs peuplée de personnages tout à fait demeurés : les Quizzies ! Choisis le tien et affronte jusqu'à 5 joueurs en direct ! </p>
	            	</section>
	            	<!-- séparation par un border de 100px largeur -->
	            	<section>
	            		<img id="qrworld" src="img\QRNewWorld.png" title="Quiz Rush nouveautée" alt="Image Quiz Rush Quizziwood" />
	            		<p>Les Quizzies sont un peu limités, avec leur mémoire de poisson rouge et leur demi-neurone. C'est donc à toi de les aider à devenir des champions du quizz de culture générale ! </p>
	            	</section>
	            	<!-- séparation par un border de 100px largeur -->
	            	<section>
	            		<img id="qrfall" src="img\QRfall.png" title="Quiz Rush attention aux chutes" alt="Image Quiz Rush attention aux chutes" />
	            		<p>Dans une course, chaque bonne réponse surexcite ton Quizzy et le fait accélérer. Une mauvaise réponse le déprime et le fait chuter !  </p>
	            	</section>
	            	<!-- petit carré en bas à droite disposition image/bloctext verticals-->
	            </div>
	        </main>