			<main>
	            <h1><strong>Nos Jeux</strong></h1>
				<div id="bloc1">
					<section>
	            		<img id="qp0" src="img\QPimg0.png" alt="Images jeu Quiz Panic" />
	            		<p>Quiz Panic est un jeu de quiz de culture générale réunissant de 2 à 20 adversaires qui s’affrontent en live.</p>
	            	</section>
	            	<section>
						<img id="qp1" src="img\QR1.png" title="Quiz Rush" alt="Image Quiz Rush" />
						<p>Quiz Rush est un jeu de quiz de culture générale réunissant de 2 à 20 adversaires qui s’affrontent en live.</p>				
	            	</section>
	            	<section>
	            		<img id="qp2" src="img\QT1.png" title="Quiz tower evenement" alt="Image Quiz tower" />
	            		<p>Quiz tower est un jeu de quiz de culture générale réunissant de 2 à 20 adversaires qui s’affrontent en live. </p>
	            	</section>
	            	<section>
	            		<img id="qp3" src="img\tmvpsp1.png" title="Tout le monde veux prendre sa place" alt="Image Tout le monde veux prendre sa place" />
	            		<p>Tout le monde veux prendre sa place est un jeu de quiz drole, d 2 à 20 adversaires qui s’affrontent en live. </p>           	
	            	</section>
	            </div>
	        </main>